### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by tonisi** [dldxzx/MMDTA#1]
Hi, I cannot run the the example code as there seem to be a file(s) missing:

python test_pretrain.py results in the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'data/distance_matrix/3ao4.npz'

Best regards, 
Toni

**Comment by dldxzx** [comment]
Please unzip the data folder "data"



Xin Zeng
Associate Professor
College of Mathematics and Computer Science, Dali University, Dali, China
Machine learning, Data mining
 
From: tonisi
Date: 2023-08-28 20:16
To: dldxzx/MMDTA
CC: Subscribed
Subject: [dldxzx/MMDTA] Missing file (Issue #1)
Hi, I cannot run the the example code as there seem to be a file(s) missing:
python test_pretrain.py results in the following error:
FileNotFoundError: [Errno 2] No such file or directory: 'data/distance_matrix/3ao4.npz'
Best regards,
Toni

**Comment by tonisi** [comment]
Thank you for the fast reply.

I did the unzip data.zip, it does not contain the folder 'distance_matrix'.

Best regards,
Toni

**Comment by dldxzx** [comment]
I'm sorry, the "distance_matrix" folder is too large. If you need it, please send me your mail address and I will sent it to you.



Xin Zeng
Associate Professor
College of Mathematics and Computer Science, Dali University, Dali, China
Machine learning, Data mining
 
From: tonisi
Date: 2023-08-28 22:19
To: dldxzx/MMDTA
CC: Xin Zeng; Comment
Subject: Re: [dldxzx/MMDTA] Missing file (Issue #1)
Thank you for the fast reply.
I did the unzip data.zip, it does not contain the folder 'distance_matrix'.
Best regards,
Toni
―

**Comment by tonisi** [comment]
Thank you, that would be most helpful, I am interested in trying your method myself.
my email is toni.sivula@uef.fi

Best regards,
Toni
