### ISSUE TITLE
关于训练数据和验证数据集

### ISSUE THREAD

**Issue by MarcoReus-1** [dldxzx/MMDTA#3]
作者您好！看了您的论文，对您的工作非常感兴趣。但我个人在跑代码的时候，发现找不到训练集和验证集，我尝试了自己到相关网站下载资源，但使用这些资源效果欠佳。请问可以提供一下训练和验证的数据吗？就是训练和验证的.smi文件，fasta文件等等。不胜感激！

**Comment by dldxzx** [comment]
distance_matrix文件太大了，无法上传至github仓库，我们在readme文件上重新加了个数据下载链接，请重新查看readme文件。



Xin Zeng
Associate Professor
College of Mathematics and Computer Science, Dali University, Dali, China
Machine learning, Data mining
 
发件人： MarcoReus-1
发送时间： 2023-09-14 16:35
收件人： dldxzx/MMDTA
抄送： Subscribed
主题： [dldxzx/MMDTA] 关于训练数据和验证数据集 (Issue #3)
作者您好！看了您的论文，对您的工作非常感兴趣。但我个人在跑代码的时候，发现找不到训练集和验证集，我尝试了自己到相关网站下载资源，但使用这些资源效果欠佳。请问可以提供一下训练和验证的数据吗？就是训练和验证的.smi文件，fasta文件等等。不胜感激！
